<?php
/**
 * Copyright © Bluethink, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php echo $block->getGridHtml(); ?>

<?php $scriptString = <<<script

require([
    'jquery',
    'mage/backend/validation',
    "prototype"
], function(jQuery){

//<![CDATA[
    jQuery('#filter_form').mage('validation', {errorClass: 'mage-error'});
    function filterFormSubmit() {
        var filters = \$$('#filter_form input', '#filter_form select'),
            elements = [];

        for (var i in filters) {
            if (filters[i].value && filters[i].value.length && !filters[i].disabled) {
                console.log(elements.push(filters[i]));
                elements.push(filters[i]);
            }
        }

        if (jQuery('#filter_form').valid()) {
            setLocation('{$block->escapeJs($block->getFilterUrl())}filter/'+
                Base64.encode(Form.serializeElements(elements))+'/'
            );
        }
    }
//]]>
    window.filterFormSubmit = filterFormSubmit;
});

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>


