
<div  data-bind="scope: 'chartscope'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "chartscope": {
                    "component": "Bluethink_AdvanceReports/js/chart"
                }
            }
        }
    }
}
</script>

<style>
    #some-simple-line-chart{
        height: 600px !important;
        width: 100% !important;
    }
</style>
